spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT}
            clientSecret: ${GITHUB_SECRET}
            scope: read:user, user:email

admin:
  users: "PieterDup98"